import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@/styles/globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { SessionProvider } from "@/providers/session"
import { QueryClientProvider } from "@/providers/query-client"
import { Toaster } from "@/components/ui/toaster"
import { getServerAuthSession } from "@/lib/server-session"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Dumi",
	description: "Generated by create next app",
	icons: [
		{
			url: "/favicon.ico",
			sizes: "16x16",
			type: "image/x-icon",
		},
		{
			url: "/assets/favicon-16x16.png",
			sizes: "16x16",
			type: "image/png",
		},
		{
			url: "/assets/favicon-32x32.png",
			sizes: "32x32",
			type: "image/png",
		},
	],
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const session = await getServerAuthSession()

	return (
		<html lang="en" suppressHydrationWarning>
			<body className={inter.className}>
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					enableSystem
					disableTransitionOnChange
				>
					<QueryClientProvider>
						<SessionProvider session={session}>{children}</SessionProvider>
					</QueryClientProvider>
				</ThemeProvider>
				<Toaster />
			</body>
		</html>
	)
}
