version: "3"
name: "dumi"
services:
  db:
    image: postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_ADMIN_USER: ${DATABASE_ROOT_USER}
      POSTGRES_ADMIN_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db_net
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
networks:
  db_net:
    driver: bridge
volumes:
  db_data:
